### ISSUE TITLE
Recipes for official ContinuumIO builds not in Anaconda

### ISSUE THREAD

**Issue by synapticarbors** [ContinuumIO/anaconda-recipes#39]
I was curious to see the `rpy2` recipe that is available via the official `R` channel, and was wondering if there were any plans to make packages that aren't in Anaconda or the main default channel publicly available?

For `rpy2` in particular, this was one of the classically difficult packages to build on Windows. Up until recently there were only conda packages for OSX and Linux, but recently a Windows build was posted to the `R` channel. It however only supports py34 and py35 so I was looking for a template to build a py27 version from (or you can also consider this an official request to build a python 2.7 package for Windows 😃  ).

**Comment by mingwandroid** [comment]
The latest version of the recipe for `rpy2` is at: https://github.com/mingwandroid/conda-recipes/tree/master/python/rpy2

Building it on Windows was fairly difficult. I hope to upstream the patches at some point.

In general we aim to make all of the recipes in the `Anaconda Distribution` available. This is a work in progress. By the way, if you look in most (all?) packages' `tar.bz2` files (or the extracted folder inside `%CONDA_PREFIX%\pkgs`, you will find the recipe and the patches in the `info` directory.

The reason for the current lack of a Python 2.7 package is due to an issue in `conda-build` which *should* be fixed tomorrow. Rest assured, as soon as I can, Python 2.7 versions of `rpy2` will be uploaded. Hopefully the Python 2.7 port won't present significant additional challenges.
